const routeList = [
  "Dhaka",
  "Biman Bandar",
  "Gafargaon",
  "Mymensingh",
  "Narundi",
  "Jamalpur Town",
  "Kendua Bazar",
  "Sarishabari",
  "Tarakandi",
];

const dataMatrix = [
  [
    null,
    [],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659096,
        route_id: 22680,
        fare: "85.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 3,
        seat_counts: {
          online: 29,
          offline: 29,
          is_divided: true,
        },
      },
    ],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659094,
        route_id: 22681,
        fare: "120.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 4,
        seat_counts: {
          online: 39,
          offline: 38,
          is_divided: true,
        },
      },
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659220,
        route_id: 22681,
        fare: "145.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 4,
        seat_counts: {
          online: 5,
          offline: 4,
          is_divided: true,
        },
      },
      {
        key: 6,
        type: "F_CHAIR",
        trip_id: 8441297,
        trip_route_id: 53659319,
        route_id: 22681,
        fare: "195.00",
        vat_percent: 15,
        vat_amount: 30,
        origin_city_seq: 1,
        destination_city_seq: 4,
        seat_counts: {
          online: 3,
          offline: 3,
          is_divided: true,
        },
      },
    ],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659100,
        route_id: 23514,
        fare: "160.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 5,
        seat_counts: {
          online: 5,
          offline: 5,
          is_divided: true,
        },
      },
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659226,
        route_id: 23514,
        fare: "190.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 5,
        seat_counts: {
          online: 3,
          offline: 2,
          is_divided: true,
        },
      },
    ],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659097,
        route_id: 22682,
        fare: "175.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 6,
        seat_counts: {
          online: 80,
          offline: 80,
          is_divided: true,
        },
      },
      {
        key: 6,
        type: "F_CHAIR",
        trip_id: 8441297,
        trip_route_id: 53659322,
        route_id: 22682,
        fare: "280.00",
        vat_percent: 15,
        vat_amount: 42,
        origin_city_seq: 1,
        destination_city_seq: 6,
        seat_counts: {
          online: 12,
          offline: 12,
          is_divided: true,
        },
      },
    ],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659101,
        route_id: 25106,
        fare: "185.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 7,
        seat_counts: {
          online: 5,
          offline: 5,
          is_divided: true,
        },
      },
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659227,
        route_id: 25106,
        fare: "220.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 7,
        seat_counts: {
          online: 3,
          offline: 2,
          is_divided: true,
        },
      },
    ],
    [
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659224,
        route_id: 22683,
        fare: "245.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 8,
        seat_counts: {
          online: 12,
          offline: 12,
          is_divided: true,
        },
      },
    ],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659099,
        route_id: 22678,
        fare: "205.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 9,
        seat_counts: {
          online: 16,
          offline: 16,
          is_divided: true,
        },
      },
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659225,
        route_id: 22678,
        fare: "245.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 9,
        seat_counts: {
          online: 3,
          offline: 2,
          is_divided: true,
        },
      },
      {
        key: 6,
        type: "F_CHAIR",
        trip_id: 8441297,
        trip_route_id: 53659324,
        route_id: 22678,
        fare: "325.00",
        vat_percent: 15,
        vat_amount: 49,
        origin_city_seq: 1,
        destination_city_seq: 9,
        seat_counts: {
          online: 2,
          offline: 2,
          is_divided: true,
        },
      },
      {
        key: 5,
        type: "F_SEAT",
        trip_id: 8441302,
        trip_route_id: 53659409,
        route_id: 22678,
        fare: "325.00",
        vat_percent: 15,
        vat_amount: 49,
        origin_city_seq: 1,
        destination_city_seq: 9,
        seat_counts: {
          online: 3,
          offline: 3,
          is_divided: true,
        },
      },
    ],
  ],
  [
    null,
    null,
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659096,
        route_id: 22680,
        fare: "85.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 3,
        seat_counts: {
          online: 29,
          offline: 29,
          is_divided: true,
        },
      },
    ],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659094,
        route_id: 22681,
        fare: "120.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 4,
        seat_counts: {
          online: 39,
          offline: 38,
          is_divided: true,
        },
      },
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659220,
        route_id: 22681,
        fare: "145.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 4,
        seat_counts: {
          online: 5,
          offline: 4,
          is_divided: true,
        },
      },
      {
        key: 6,
        type: "F_CHAIR",
        trip_id: 8441297,
        trip_route_id: 53659319,
        route_id: 22681,
        fare: "195.00",
        vat_percent: 15,
        vat_amount: 30,
        origin_city_seq: 1,
        destination_city_seq: 4,
        seat_counts: {
          online: 3,
          offline: 3,
          is_divided: true,
        },
      },
    ],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659100,
        route_id: 23514,
        fare: "160.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 5,
        seat_counts: {
          online: 5,
          offline: 5,
          is_divided: true,
        },
      },
    ],
    [
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659223,
        route_id: 22682,
        fare: "210.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 6,
        seat_counts: {
          online: 26,
          offline: 25,
          is_divided: true,
        },
      },
      {
        key: 5,
        type: "F_SEAT",
        trip_id: 8441302,
        trip_route_id: 53659407,
        route_id: 22682,
        fare: "280.00",
        vat_percent: 15,
        vat_amount: 42,
        origin_city_seq: 1,
        destination_city_seq: 6,
        seat_counts: {
          online: 6,
          offline: 6,
          is_divided: true,
        },
      },
    ],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659101,
        route_id: 25106,
        fare: "185.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 7,
        seat_counts: {
          online: 5,
          offline: 5,
          is_divided: true,
        },
      },
    ],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659098,
        route_id: 22683,
        fare: "205.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 8,
        seat_counts: {
          online: 40,
          offline: 40,
          is_divided: true,
        },
      },
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659224,
        route_id: 22683,
        fare: "245.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 8,
        seat_counts: {
          online: 12,
          offline: 12,
          is_divided: true,
        },
      },
      {
        key: 6,
        type: "F_CHAIR",
        trip_id: 8441297,
        trip_route_id: 53659323,
        route_id: 22683,
        fare: "325.00",
        vat_percent: 15,
        vat_amount: 49,
        origin_city_seq: 1,
        destination_city_seq: 8,
        seat_counts: {
          online: 8,
          offline: 7,
          is_divided: true,
        },
      },
    ],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659099,
        route_id: 22678,
        fare: "205.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 9,
        seat_counts: {
          online: 16,
          offline: 16,
          is_divided: true,
        },
      },
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659225,
        route_id: 22678,
        fare: "245.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 1,
        destination_city_seq: 9,
        seat_counts: {
          online: 3,
          offline: 2,
          is_divided: true,
        },
      },
      {
        key: 6,
        type: "F_CHAIR",
        trip_id: 8441297,
        trip_route_id: 53659324,
        route_id: 22678,
        fare: "325.00",
        vat_percent: 15,
        vat_amount: 49,
        origin_city_seq: 1,
        destination_city_seq: 9,
        seat_counts: {
          online: 2,
          offline: 2,
          is_divided: true,
        },
      },
      {
        key: 5,
        type: "F_SEAT",
        trip_id: 8441302,
        trip_route_id: 53659409,
        route_id: 22678,
        fare: "325.00",
        vat_percent: 15,
        vat_amount: 49,
        origin_city_seq: 1,
        destination_city_seq: 9,
        seat_counts: {
          online: 3,
          offline: 3,
          is_divided: true,
        },
      },
    ],
  ],
  [
    null,
    null,
    null,
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659113,
        route_id: 22688,
        fare: "45.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 3,
        destination_city_seq: 4,
        seat_counts: {
          online: 15,
          offline: 15,
          is_divided: true,
        },
      },
    ],
    [],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659114,
        route_id: 27225,
        fare: "95.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 3,
        destination_city_seq: 6,
        seat_counts: {
          online: 15,
          offline: 14,
          is_divided: true,
        },
      },
    ],
    [],
    [],
    [],
  ],
  [
    null,
    null,
    null,
    null,
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659105,
        route_id: 27226,
        fare: "45.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 4,
        destination_city_seq: 5,
        seat_counts: {
          online: 5,
          offline: 5,
          is_divided: true,
        },
      },
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659231,
        route_id: 27226,
        fare: "50.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 4,
        destination_city_seq: 5,
        seat_counts: {
          online: 3,
          offline: 2,
          is_divided: true,
        },
      },
    ],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659102,
        route_id: 22689,
        fare: "55.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 4,
        destination_city_seq: 6,
        seat_counts: {
          online: 42,
          offline: 41,
          is_divided: true,
        },
      },
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659228,
        route_id: 22689,
        fare: "65.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 4,
        destination_city_seq: 6,
        seat_counts: {
          online: 5,
          offline: 4,
          is_divided: true,
        },
      },
      {
        key: 6,
        type: "F_CHAIR",
        trip_id: 8441297,
        trip_route_id: 53659325,
        route_id: 22689,
        fare: "90.00",
        vat_percent: 15,
        vat_amount: 14,
        origin_city_seq: 4,
        destination_city_seq: 6,
        seat_counts: {
          online: 5,
          offline: 5,
          is_divided: true,
        },
      },
      {
        key: 5,
        type: "F_SEAT",
        trip_id: 8441302,
        trip_route_id: 53659410,
        route_id: 22689,
        fare: "90.00",
        vat_percent: 15,
        vat_amount: 14,
        origin_city_seq: 4,
        destination_city_seq: 6,
        seat_counts: {
          online: 3,
          offline: 3,
          is_divided: true,
        },
      },
    ],
    [],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659103,
        route_id: 22690,
        fare: "85.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 4,
        destination_city_seq: 8,
        seat_counts: {
          online: 8,
          offline: 7,
          is_divided: true,
        },
      },
    ],
    [],
  ],
  [
    null,
    null,
    null,
    null,
    null,
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659118,
        route_id: 27227,
        fare: "45.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 5,
        destination_city_seq: 6,
        seat_counts: {
          online: 10,
          offline: 10,
          is_divided: true,
        },
      },
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659241,
        route_id: 27227,
        fare: "50.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 5,
        destination_city_seq: 6,
        seat_counts: {
          online: 5,
          offline: 5,
          is_divided: true,
        },
      },
    ],
    [],
    [],
    [],
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    [],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659115,
        route_id: 22692,
        fare: "45.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 6,
        destination_city_seq: 8,
        seat_counts: {
          online: 113,
          offline: 112,
          is_divided: true,
        },
      },
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659238,
        route_id: 22692,
        fare: "50.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 6,
        destination_city_seq: 8,
        seat_counts: {
          online: 30,
          offline: 30,
          is_divided: true,
        },
      },
      {
        key: 6,
        type: "F_CHAIR",
        trip_id: 8441297,
        trip_route_id: 53659333,
        route_id: 22692,
        fare: "90.00",
        vat_percent: 15,
        vat_amount: 14,
        origin_city_seq: 6,
        destination_city_seq: 8,
        seat_counts: {
          online: 13,
          offline: 12,
          is_divided: true,
        },
      },
    ],
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659116,
        route_id: 22693,
        fare: "45.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 6,
        destination_city_seq: 9,
        seat_counts: {
          online: 35,
          offline: 35,
          is_divided: true,
        },
      },
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659239,
        route_id: 22693,
        fare: "50.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 6,
        destination_city_seq: 9,
        seat_counts: {
          online: 10,
          offline: 10,
          is_divided: true,
        },
      },
      {
        key: 6,
        type: "F_CHAIR",
        trip_id: 8441297,
        trip_route_id: 53659334,
        route_id: 22693,
        fare: "90.00",
        vat_percent: 15,
        vat_amount: 14,
        origin_city_seq: 6,
        destination_city_seq: 9,
        seat_counts: {
          online: 5,
          offline: 5,
          is_divided: true,
        },
      },
      {
        key: 5,
        type: "F_SEAT",
        trip_id: 8441302,
        trip_route_id: 53659419,
        route_id: 22693,
        fare: "90.00",
        vat_percent: 15,
        vat_amount: 14,
        origin_city_seq: 6,
        destination_city_seq: 9,
        seat_counts: {
          online: 9,
          offline: 9,
          is_divided: true,
        },
      },
    ],
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659120,
        route_id: 27216,
        fare: "45.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 7,
        destination_city_seq: 8,
        seat_counts: {
          online: 5,
          offline: 5,
          is_divided: true,
        },
      },
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659243,
        route_id: 27216,
        fare: "50.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 7,
        destination_city_seq: 8,
        seat_counts: {
          online: 3,
          offline: 2,
          is_divided: true,
        },
      },
    ],
    [],
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    [
      {
        key: 8,
        type: "SHOVAN",
        trip_id: 8441287,
        trip_route_id: 53659117,
        route_id: 22694,
        fare: "45.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 8,
        destination_city_seq: 9,
        seat_counts: {
          online: 165,
          offline: 165,
          is_divided: true,
        },
      },
      {
        key: 7,
        type: "S_CHAIR",
        trip_id: 8441292,
        trip_route_id: 53659240,
        route_id: 22694,
        fare: "50.00",
        vat_percent: 0,
        vat_amount: 0,
        origin_city_seq: 8,
        destination_city_seq: 9,
        seat_counts: {
          online: 48,
          offline: 47,
          is_divided: true,
        },
      },
      {
        key: 6,
        type: "F_CHAIR",
        trip_id: 8441297,
        trip_route_id: 53659335,
        route_id: 22694,
        fare: "90.00",
        vat_percent: 15,
        vat_amount: 14,
        origin_city_seq: 8,
        destination_city_seq: 9,
        seat_counts: {
          online: 20,
          offline: 20,
          is_divided: true,
        },
      },
    ],
  ],
  [null, null, null, null, null, null, null, null, null],
];
